### ISSUE TITLE
Move all required python packages from notes to requirements.txt file

### ISSUE THREAD

**Issue by Nutek** [Xeverous/the_website#21]
Why and for what:
- Each python application/website/whatever should have requirements.txt file to point python dependencies
- Preparation of environment is much simpler with that file

Syntax of requirements.txt file is similar to output of command: `pip freeze`

Any example of use or implementation:
To install all required packages:
`pip install -r requirements.txt`

BTW: Usage of `virtualenv` should be a choice, not a requirement. This project could work without `virtualenv` as well.

**Comment by Xeverous** [comment]
Virtual env is not strictly required, I can state that in the docs.

Turns out I actually did not commit the requirements file, I can check what `pip freeze` outputs for me - I guess there will be few libraries which aren't required at all (just leftovers from some past experiments).

**Comment by Nutek** [comment]
Any way I believe `requirements.txt` could help to setup environment.

**Comment by Xeverous** [comment]
done in fe6e83b3123429c962536ff5c16436613577ec13
